from __future__ import annotations

import datetime as dt
from typing import Any

from src.checks.static_checks import StaticCheckReport
from src.checks.dynamic_checks import DynamicCheckReport
from src.checks.scoring import ScoreResult
from src.mcp_client import MCPProbeResult

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
SEVERITY_EMOJI = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}


def build_report_dict(
    server_url: str,
    probe: MCPProbeResult,
    static_report: StaticCheckReport,
    dynamic_report: DynamicCheckReport | None,
    score: ScoreResult,
) -> dict[str, Any]:
    all_findings = list(static_report.findings)
    if dynamic_report:
        all_findings += dynamic_report.findings
    all_findings.sort(key=lambda f: SEVERITY_ORDER.get(f.severity, 9))

    return {
        "scanned_at": dt.datetime.utcnow().isoformat() + "Z",
        "server_url": server_url,
        "server_name": probe.server_name,
        "protocol_version": probe.protocol_version,
        "reachable": probe.reachable,
        "tool_count": len(probe.tools),
        "score": score.score,
        "grade": score.grade,
        "summary": {
            "tools_with_secrets": static_report.tools_with_secrets,
            "tools_with_injection_risk": static_report.tools_with_injection_risk,
            "tools_with_ssrf_prone_params": static_report.tools_with_ssrf_prone_params,
            "tools_with_poor_schema": static_report.tools_with_poor_schema,
            "dynamic_checks_run": dynamic_report is not None,
            "ssrf_suspicious_tools": dynamic_report.ssrf_suspicious_tools if dynamic_report else None,
            "unauth_accessible_tools": dynamic_report.unauth_accessible_tools if dynamic_report else None,
            "stack_trace_leaks": dynamic_report.stack_trace_leaks if dynamic_report else None,
        },
        "findings": [
            {
                "severity": f.severity,
                "category": f.category,
                "tool": f.tool,
                "message": f.message,
            }
            for f in all_findings
        ],
    }


def build_markdown_report(report: dict[str, Any]) -> str:
    lines = []
    lines.append(f"# MCP Security & Trust Report")
    lines.append("")
    lines.append(f"**Server:** `{report['server_url']}`")
    if report.get("server_name"):
        lines.append(f"**Name:** {report['server_name']}")
    lines.append(f"**Scanned at:** {report['scanned_at']}")
    lines.append(f"**Tools exposed:** {report['tool_count']}")
    lines.append("")
    lines.append(f"## Score: {report['score']}/100 (Grade {report['grade']})")
    lines.append("")

    if not report["reachable"]:
        lines.append("⚠️ **Server was not reachable — scan incomplete.**")
        return "\n".join(lines)

    s = report["summary"]
    lines.append("## Summary")
    lines.append(f"- Tools with possible secret leaks: **{s['tools_with_secrets']}**")
    lines.append(f"- Tools with prompt-injection-style language: **{s['tools_with_injection_risk']}**")
    lines.append(f"- Tools with SSRF-prone parameters: **{s['tools_with_ssrf_prone_params']}**")
    lines.append(f"- Tools with weak/missing schema docs: **{s['tools_with_poor_schema']}**")
    if s["dynamic_checks_run"]:
        lines.append(f"- Confirmed/unclear SSRF behavior on live test: **{s['ssrf_suspicious_tools']}**")
        lines.append(f"- Tools reachable without auth: **{s['unauth_accessible_tools']}**")
        lines.append(f"- Stack-trace leaks on malformed input: **{s['stack_trace_leaks']}**")
    else:
        lines.append("- Dynamic (live) checks: **not run**")
    lines.append("")

    lines.append("## Findings")
    if not report["findings"]:
        lines.append("No findings. 🎉")
    for f in report["findings"]:
        emoji = SEVERITY_EMOJI.get(f["severity"], "")
        tool_part = f" (`{f['tool']}`)" if f["tool"] else ""
        lines.append(f"- {emoji} **[{f['severity'].upper()}]** {f['category']}{tool_part}: {f['message']}")

    lines.append("")
    lines.append("---")
    lines.append(
        "_Generated by MCP Security Scanner. This is an automated heuristic scan, "
        "not a substitute for a full manual security audit._"
    )
    return "\n".join(lines)
